### ISSUE TITLE
[Feature request] Don't throw at config time

### ISSUE THREAD

**Issue by msencenb** [pusher/push-notifications-ruby#18]
I integrated this gem into my app today, works great on local. 

In my test pipeline (Heroku CI currently), my build fails because the initializer is receiving nil for the secret key and instance id:

```
Pusher::PushNotifications.configure do |config|
  config.instance_id = ENV['PUSHER_INSTANCE_ID']
  config.secret_key = ENV['PUSHER_SECRET_KEY']
end
```

That code throws if nothing is passed in:
```
      def instance_id=(instance_id)
        if instance_id.nil? || instance_id.delete(' ').empty?
          raise PushError, 'Invalid instance id'
        end
        @instance_id = instance_id
      end
```

Most ruby libraries I've interacted with don't throw at config/initialize time, they throw at runtime. 

In this case I explicitly do not want to enter a valid pusher configuration to the test runner. This is a relatively easy fix for me as I can put in garbage env variables to the test runner or rescue the exception in the initializer. 

But it's also going to force me to ensure every environment I ever spin up has some sort of beams credentials or else the entire app will fail to build/launch. In plenty of environments I don't need beams at all, it would be great if that exception could either be suppressed or if it didn't raise at all imho.

**Comment by WillSewell** [comment]
Thank you for highlighting this. In the meantime you should be able to pass in a dummy instance_id:

```
Pusher::PushNotifications.configure do |config|
   config.secret_key = "foo"
   config.instance_id = "foo"
end
=> #<Module:0x00007f837c9cddd8>
Pusher::PushNotifications.publish_to_interests(interests: ['hello'], payload: data)
=> #<struct Pusher::PushNotifications::Client::Response
 status=400,
 content=
  {"error"=>"Bad request",
   "description"=>"The instance id given is invalid. It is expected to be in this format: '3162fe0d-5518-48bf-9ce1-961a7229a2ff'."},
 ok?=false>
```

**Comment by elverkilde** [comment]
> But it's also going to force me to ensure every environment I ever spin up has some sort of beams credentials or else the entire app will fail to build/launch.

I mostly see this as a feature tbh, raising the exception as early as possible seems like a good idea. Since it's possible to insert fake credentials, I think it should be relatively easy to work around. I will close this as a `wontfix`, but please feel free to re-open this if you feel strongly about it (and if more people require this feature).
