### ISSUE TITLE
Unable to use configuration for multiple clients

### ISSUE THREAD

**Issue by jereinhardt** [pusher/push-notifications-ruby#28]
According to the documentation

> if multiple clients are needed, store the reference that is returned from the configure method.

If I am interpreting the instructions correctly, I take this to mean that, if you need to establish multiple clients in the same application.  The way you are meant to configure those clients and publish to interests through those clients is like so:

```ruby
client_a = Pusher::PushNotifications.configure do |config|
  config.instance_id = 'client-a-instance-id'
  config.secret_key = 'client-a-secret'
end

client_b = Pusher::PushNotifications.configure do |config|
  config.instance_id = 'client-b-instance-id'
  config.secret_key = 'client-b-secret'
end
```

and then to publish to an interest through one of those clients, you would do so like this:

```ruby
 client_a.publish_to_interests(interests: ['interest'], payload: {})
```

However, I have found that after setting up my application this way, all interests are published through the client that was configured last, and that saving the returned module from `configure` and using that module to publish push notifications does not seem to determine which client is used.

I am wondering if I am unclear on how multiple clients are meant to be configured and used in a single application.  If that is the case, it may be helpful to make the documentation more clear so other can avoid the same confusion (unless I am just extremely dense, which is a possibility).  However, if what I outlined above is how multiple clients are meant to be used, then there seems to be some issue in how the configuration for those clients are saved.

**Comment by benjamin-tang-pusher** [comment]
I get the same, I will see if this is an issue with the lib, or we're just doing it the wrong way.

**Comment by benjamin-tang-pusher** [comment]
We might have a potential bug. Looking into fixing it...
