### ISSUE TITLE
 NoMethodError on Pusher::PushNotifications.publish_to_interests

### ISSUE THREAD

**Issue by israelcoper** [pusher/push-notifications-ruby#32]
## Error:
```
NoMethodError: undefined method `match?' for /^(_|\-|=|@|,|\.|:|[A-Z]|[a-z]|[0-9])*$/:Regexp
Did you mean?  match
from /HOME/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/pusher-push-notifications-1.3.0/lib/pusher/push_notifications/use_cases/publish.rb:24:in `block in initialize'
```

## Version
`pusher-push-notifications-1.3.0`

## Configuration
```
Pusher::PushNotifications.configure do |config|
  config.instance_id = "PUSHER_BEAMS_INSTANCE_ID"
  config.secret_key = "PUSHER_SECRET_KEY"
end
```

## Sample request
```
payload = {
    web: {
      notification: {
        title: 'Hello',
        body: 'Hello, world!',
        deep_link: 'http://localhost:4567'
      }
    }
}

Pusher::PushNotifications.publish_to_interests(interests: ['hello'], payload: payload)
```

#### Pusher::PushNotifications.publish_to_users works fine

**Comment by benw-pusher** [comment]
I've run the same code and encountered a different result - the notification was published ok. This suggests the issue could be environmental. 
Can you confirm the ruby version in use? It looks to be Ruby 2.3 which I believe is now EOL. 
For reference, my env is using `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`.

**Comment by israelcoper** [comment]
Upgrading ruby version fixed this issue. Thanks.

Here's my upgraded ruby version: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]`
